export interface Workspace { id: string; name: string; path: string; prompt: string; createdAt: string; updatedAt: string }
export interface Bot { id: string; name: string; description: string; appId: string; hasAppSecret: boolean; prompt: string; permissions: string[]; operatorIds: string[]; conversationMode: 'chat' | 'topic'; defaultWorkspaceId: string; workspaceIds: string[]; createdAt: string; updatedAt: string }
export interface Matcher { chatIds: string[]; messageTypes: string[]; textIncludes: string[]; cardTitleIncludes: string[] }
export interface Scene { id: string; botId: string; workspaceId: string; name: string; prompt: string; priority: number; enabled: boolean; matcher: Matcher; skillPackageIds: string[]; createdAt: string; updatedAt: string }
export interface SkillPackage { id: string; workspaceId: string; name: string; description: string; prompt: string; skills: string[]; fallbackMode: 'package_first' | 'mixed' | 'package_only'; createdAt: string; updatedAt: string }
export interface ProvisioningJob { id: string; status: 'starting'|'waiting_scan'|'creating'|'completed'|'failed'|'cancelled'; qrUrl: string; expiresAt: string; error: string; botId: string; createdAt: string; updatedAt: string }
export interface MessageLog { id: string; eventId: string; messageId: string; botId: string; botName: string; chatId: string; topicId: string; senderId: string; messageType: string; inboundContent: string; responseContent: string; status: 'processing'|'completed'|'failed'; error: string; workspaceId: string; workspaceName: string; sceneId: string; sceneName: string; skillPackages: Array<{ id: string; name: string }>; receivedAt: string; startedAt: string; completedAt: string; durationMs: number|null }
export interface AdminAccount { id: string; loginName: string; displayName: string; primary: boolean; enabled: boolean; lastLoginAt: string; createdAt: string; updatedAt: string }
export interface AuditLog { id: string; actorAccountId: string; actorLoginName: string; actorDisplayName: string; action: string; targetType: string; targetId: string; summary: string; details: Record<string, unknown>; ipAddress: string; createdAt: string }
export interface ChatMetadata { botId: string; chatId: string; name: string; mode: 'group'|'topic'|'p2p'; updatedAt: string }
export interface ConversationThread { id: string; botId: string; botName: string; conversationMode: 'chat'|'topic'; chatId: string; chatName: string; chatMode: ChatMetadata['mode']|''; topicId: string; coreThreadId: string; createdAt: string; updatedAt: string }
