<script setup lang="ts">
import { Pencil, Plus, Trash2, Wrench, X } from 'lucide-vue-next'
import { onMounted, reactive, ref } from 'vue'
import { api } from '../api'
import PaginationBar from '../components/PaginationBar.vue'
import type { Tool, Workspace } from '../types'
const pageSize = 20
const items = ref<Tool[]>([]), workspaces = ref<Workspace[]>([]), total = ref(0), offset = ref(0), loading = ref(false), open = ref(false), saving = ref(false), error = ref('')
const form = reactive({ id: '', workspaceId: '', name: '', description: '', executorType: 'bits_rpc' as Tool['executorType'], command: 'bits', argumentsText: 'rpc\ncall\n{{service}}\n{{method}}\n--input\n{{json}}', schemaText: '{\n  "type": "object",\n  "properties": {}\n}', timeoutSeconds: 60, enabled: true })
const load = async () => { loading.value = true; try { const [page, spaces] = await Promise.all([api.toolsPage(pageSize, offset.value), api.workspaces()]); items.value = page.items; total.value = page.total; workspaces.value = spaces } finally { loading.value = false } }
onMounted(load)
const edit = (item?: Tool) => { Object.assign(form, item ? { ...item, argumentsText: item.argumentsTemplate.join('\n'), schemaText: JSON.stringify(item.inputSchema, null, 2) } : { id: '', workspaceId: workspaces.value[0]?.id ?? '', name: '', description: '', executorType: 'bits_rpc', command: 'bits', argumentsText: 'rpc\ncall\n{{service}}\n{{method}}\n--input\n{{json}}', schemaText: '{\n  "type": "object",\n  "properties": {}\n}', timeoutSeconds: 60, enabled: true }); error.value = ''; open.value = true }
const save = async () => { saving.value = true; error.value = ''; try { const inputSchema = JSON.parse(form.schemaText || '{}') as Record<string, unknown>; await api.saveTool({ ...form, argumentsTemplate: form.argumentsText.split('\n').map(v => v.trim()).filter(Boolean), inputSchema }); open.value = false; await load() } catch (e) { error.value = e instanceof Error ? e.message : '保存失败' } finally { saving.value = false } }
const remove = async (item: Tool) => { if (!confirm(`删除工具“${item.name}”？`)) return; try { await api.deleteTool(item.id); await load() } catch (e) { alert(e instanceof Error ? e.message : '删除失败') } }
const workspaceName = (id: string) => workspaces.value.find(item => item.id === id)?.name ?? '未知工作区'
</script>
<template><div class="page">
  <header class="page-header"><div><p class="eyebrow">Atomic operations</p><h1>工具</h1><p class="page-description">注册一个可审计的原子接口。命令以参数数组执行，不经过 Shell；用 <code v-text="'{{field}}'" /> 引用运行参数，<code v-text="'{{json}}'" /> 传入完整 JSON。</p></div><button class="button" :disabled="!workspaces.length" @click="edit()"><Plus :size="17" />注册工具</button></header>
  <section class="panel"><div class="panel-header"><h2>工具注册表</h2><span class="badge gray">{{ total }} 个</span></div><div v-if="!loading&&!items.length" class="empty"><Wrench :size="32" /><strong>还没有工具</strong><span>先注册 Bits RPC 或其他安全命令，再组合成工具包。</span></div><div v-else class="table-wrap"><table><thead><tr><th>名称</th><th>工作区</th><th>执行器</th><th>命令</th><th>状态</th><th /></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td><div class="entity-title">{{ item.name }}</div><div class="entity-subtitle">{{ item.description || '暂无描述' }}</div></td><td><span class="badge">{{ workspaceName(item.workspaceId) }}</span></td><td><span class="badge gray">{{ item.executorType === 'bits_rpc' ? 'Bits RPC' : '命令' }}</span></td><td><code>{{ item.command }} {{ item.argumentsTemplate.slice(0,3).join(' ') }}</code></td><td><span class="badge" :class="{gray:!item.enabled}">{{ item.enabled?'启用':'停用' }}</span></td><td><div class="actions"><button class="ghost-button" @click="edit(item)"><Pencil :size="15" />编辑</button><button class="danger-button" @click="remove(item)"><Trash2 :size="15" /></button></div></td></tr></tbody></table></div><PaginationBar :total="total" :offset="offset" :page-size="pageSize" :loading="loading" @change="value=>{offset=value;load()}" /></section>
  <div v-if="open" class="dialog-backdrop" @mousedown.self="open=false"><form class="dialog large" @submit.prevent="save"><header class="dialog-header"><div><h2>{{ form.id?'编辑工具':'注册工具' }}</h2><p>接口参数和超时会成为执行边界。</p></div><button type="button" class="icon-button" @click="open=false"><X :size="19" /></button></header><div class="dialog-body">
    <div class="field-grid"><div class="field"><label>名称</label><input v-model.trim="form.name" required placeholder="例如：冻结预算" /></div><div class="field"><label>工作区</label><select v-model="form.workspaceId" required><option v-for="space in workspaces" :key="space.id" :value="space.id">{{ space.name }}</option></select></div></div>
    <div class="field"><label>描述</label><input v-model.trim="form.description" placeholder="这个工具做什么、何时允许调用" /></div>
    <div class="field-grid"><div class="field"><label>执行器</label><select v-model="form.executorType"><option value="bits_rpc">Bits RPC</option><option value="command">本地命令</option></select></div><div class="field"><label>可执行文件</label><input v-model.trim="form.command" required class="mono" placeholder="bits" /></div></div>
    <div class="field"><label>参数模板（每行一个 argv）</label><textarea v-model="form.argumentsText" rows="7" class="mono" required /></div>
    <div class="field"><label>输入 JSON Schema</label><textarea v-model="form.schemaText" rows="8" class="mono" /></div>
    <div class="field-grid"><div class="field"><label>超时（秒）</label><input v-model.number="form.timeoutSeconds" type="number" min="1" max="900" /></div><label class="check-card"><input v-model="form.enabled" type="checkbox" /><span><strong>启用工具</strong><small>停用后所有工具包都不能执行它。</small></span></label></div>
    <div v-if="error" class="error-banner">{{ error }}</div></div><footer class="dialog-actions"><button type="button" class="ghost-button" @click="open=false">取消</button><button class="button" :disabled="saving">{{saving?'保存中…':'保存工具'}}</button></footer></form></div>
</div></template>
