<script setup lang="ts">
import { ArrowDown, ArrowUp, Pencil, Plus, ShieldCheck, Trash2, X } from 'lucide-vue-next'
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { api } from '../api'
import PaginationBar from '../components/PaginationBar.vue'
import type { Tool, ToolPackage, ToolPackageExecution, Workspace } from '../types'
type StepForm = { toolId: string; phase: 'precheck'|'execute'|'verify'; argumentsText: string }
const pageSize=20
const items=ref<ToolPackage[]>([]), executions=ref<ToolPackageExecution[]>([]), tools=ref<Tool[]>([]), workspaces=ref<Workspace[]>([]), total=ref(0), offset=ref(0), open=ref(false), saving=ref(false), error=ref('')
const form=reactive({ id:'', workspaceId:'', name:'', description:'', prompt:'', approvalRequired:true, approverText:'', cardTitle:'', cardDescription:'', enabled:true, steps:[] as StepForm[] })
const availableTools=computed(()=>tools.value.filter(item=>item.workspaceId===form.workspaceId))
const load=async()=>{ const [page, spaces, toolItems, runs]=await Promise.all([api.toolPackagesPage(pageSize,offset.value),api.workspaces(),api.tools(),api.toolPackageExecutions(10,0)]);items.value=page.items;total.value=page.total;workspaces.value=spaces;tools.value=toolItems;executions.value=runs.items }
onMounted(load)
const edit=(item?:ToolPackage)=>{Object.assign(form,item?{...item,approverText:item.approverIds.join('\n'),steps:item.steps.map(step=>({toolId:step.toolId,phase:step.phase,argumentsText:JSON.stringify(step.arguments,null,2)}))}:{id:'',workspaceId:workspaces.value[0]?.id??'',name:'',description:'',prompt:'',approvalRequired:true,approverText:'',cardTitle:'',cardDescription:'',enabled:true,steps:[]});error.value='';open.value=true}
watch(()=>form.workspaceId,()=>{form.steps=form.steps.filter(step=>availableTools.value.some(tool=>tool.id===step.toolId))})
const addStep=()=>{const tool=availableTools.value[0];if(tool)form.steps.push({toolId:tool.id,phase:'execute',argumentsText:'{}'})}
const moveStep=(index:number,delta:number)=>{const target=index+delta;if(target<0||target>=form.steps.length)return;[form.steps[index],form.steps[target]]=[form.steps[target]!,form.steps[index]! ]}
const save=async()=>{saving.value=true;error.value='';try{const steps=form.steps.map(step=>({...step,arguments:JSON.parse(step.argumentsText||'{}')}));await api.saveToolPackage({...form,approverIds:form.approverText.split('\n').map(v=>v.trim()).filter(Boolean),steps});open.value=false;await load()}catch(e){error.value=e instanceof Error?e.message:'保存失败'}finally{saving.value=false}}
const remove=async(item:ToolPackage)=>{if(!confirm(`删除工具包“${item.name}”？`))return;try{await api.deleteToolPackage(item.id);await load()}catch(e){alert(e instanceof Error?e.message:'删除失败')}}
const workspaceName=(id:string)=>workspaces.value.find(item=>item.id===id)?.name??'未知工作区'
const statusLabel=(value:ToolPackageExecution['status'])=>({awaiting_approval:'待确认',queued:'排队中',running:'执行中',completed:'已完成',failed:'失败',rejected:'已拒绝'}[value])
</script>
<template><div class="page">
  <header class="page-header"><div><p class="eyebrow">Governed workflows</p><h1>工具包</h1><p class="page-description">把多个原子工具编排成可审批流程。Codex 负责判断何时调用，平台负责权限、卡片确认、串行执行和审计。</p></div><button class="button" :disabled="!tools.length" @click="edit()"><Plus :size="17" />创建工具包</button></header>
  <section class="panel"><div class="panel-header"><h2>工具包编排</h2><span class="badge gray">{{total}} 个</span></div><div v-if="!items.length" class="empty"><ShieldCheck :size="32"/><strong>还没有工具包</strong><span>注册工具后，把预检、执行和校验步骤组合起来。</span></div><div v-else class="table-wrap"><table><thead><tr><th>名称</th><th>工作区</th><th>流程</th><th>确认</th><th>状态</th><th /></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td><div class="entity-title">{{item.name}}</div><div class="entity-subtitle">{{item.description||'暂无描述'}}</div></td><td><span class="badge">{{workspaceName(item.workspaceId)}}</span></td><td><span v-for="step in item.steps" :key="`${step.position}:${step.toolId}`" class="badge gray">{{step.phase}} · {{step.toolName}}</span></td><td>{{item.approvalRequired?`${item.approverIds.length||'管理员'} 人可确认`:'无需确认'}}</td><td><span class="badge" :class="{gray:!item.enabled}">{{item.enabled?'启用':'停用'}}</span></td><td><div class="actions"><button class="ghost-button" @click="edit(item)"><Pencil :size="15"/>编辑</button><button class="danger-button" @click="remove(item)"><Trash2 :size="15"/></button></div></td></tr></tbody></table></div><PaginationBar :total="total" :offset="offset" :page-size="pageSize" @change="value=>{offset=value;load()}" /></section>
  <section class="panel"><div class="panel-header"><div><h2>最近执行</h2><p>审批、执行和原 Thread 续跑状态。</p></div><span class="badge gray">最近 10 条</span></div><div v-if="!executions.length" class="empty compact"><span>暂无工具包执行记录</span></div><div v-else class="table-wrap"><table><thead><tr><th>时间</th><th>工具包</th><th>状态</th><th>确认人</th><th>Thread</th><th>错误</th></tr></thead><tbody><tr v-for="run in executions" :key="run.id"><td>{{new Date(run.createdAt).toLocaleString()}}</td><td><div class="entity-title">{{run.toolPackageName}}</div><code>{{run.id}}</code></td><td><span class="badge">{{statusLabel(run.status)}}</span></td><td><code>{{run.approvedBy||'—'}}</code></td><td><code>{{run.coreThreadId||run.threadChannelId}}</code></td><td>{{run.error||'—'}}</td></tr></tbody></table></div></section>
  <div v-if="open" class="dialog-backdrop" @mousedown.self="open=false"><form class="dialog large" @submit.prevent="save"><header class="dialog-header"><div><h2>{{form.id?'编辑工具包':'创建工具包'}}</h2><p>步骤顺序固定，运行时不会让模型自由拼接命令。</p></div><button type="button" class="icon-button" @click="open=false"><X :size="19"/></button></header><div class="dialog-body">
    <div class="field-grid"><div class="field"><label>名称</label><input v-model.trim="form.name" required /></div><div class="field"><label>工作区</label><select v-model="form.workspaceId" required><option v-for="space in workspaces" :key="space.id" :value="space.id">{{space.name}}</option></select></div></div>
    <div class="field"><label>描述</label><input v-model.trim="form.description" /></div><div class="field"><label>工具包 Prompt</label><textarea v-model="form.prompt" rows="5" placeholder="何时使用、调用前需要哪些证据、成功后如何校验…" /></div>
    <div class="field"><div class="section-title-row"><label>执行步骤</label><button type="button" class="ghost-button" :disabled="!availableTools.length" @click="addStep"><Plus :size="15"/>添加步骤</button></div><div v-for="(step,index) in form.steps" :key="index" class="step-editor"><span class="mono">{{index+1}}</span><select v-model="step.phase"><option value="precheck">预检</option><option value="execute">执行</option><option value="verify">校验</option></select><select v-model="step.toolId"><option v-for="tool in availableTools" :key="tool.id" :value="tool.id">{{tool.name}}</option></select><input v-model="step.argumentsText" class="mono" placeholder='固定参数 JSON，例如 {"region":"CN"}'/><button type="button" class="icon-button" @click="moveStep(index,-1)"><ArrowUp :size="15"/></button><button type="button" class="icon-button" @click="moveStep(index,1)"><ArrowDown :size="15"/></button><button type="button" class="danger-button" @click="form.steps.splice(index,1)"><Trash2 :size="15"/></button></div></div>
    <label class="check-card"><input v-model="form.approvalRequired" type="checkbox"/><span><strong>执行前需要飞书确认</strong><small>卡片点击会校验飞书回调中的真实操作人 ID。</small></span></label>
    <div v-if="form.approvalRequired" class="field"><label>有权确认的飞书 Open ID（每行一个）</label><textarea v-model="form.approverText" rows="4" class="mono" placeholder="ou_xxx\nou_yyy"/><small>留空时使用 Bot 操作人；Bot 也未配置操作人时使用应用管理员。</small></div>
    <div class="field-grid"><div class="field"><label>确认卡片标题</label><input v-model.trim="form.cardTitle" placeholder="确认执行高风险操作"/></div><div class="field"><label>卡片说明</label><input v-model.trim="form.cardDescription" placeholder="影响范围与注意事项"/></div></div>
    <label class="check-card"><input v-model="form.enabled" type="checkbox"/><span><strong>启用工具包</strong><small>停用后不会暴露给 Codex。</small></span></label><div v-if="error" class="error-banner">{{error}}</div>
  </div><footer class="dialog-actions"><button type="button" class="ghost-button" @click="open=false">取消</button><button class="button" :disabled="saving||!form.steps.length">{{saving?'保存中…':'保存工具包'}}</button></footer></form></div>
</div></template>
<style scoped>.step-editor{display:grid;grid-template-columns:36px 100px minmax(150px,1fr) minmax(200px,1.5fr) 36px 36px 42px;gap:8px;align-items:center;margin:8px 0}.section-title-row{display:flex;justify-content:space-between;align-items:center}@media(max-width:900px){.step-editor{grid-template-columns:1fr}.step-editor>span{display:none}}</style>
